namespace Origo.Bifrost.SubscriptionBilling;

/// <summary>
/// Shared Markdown help text for the <c>Subscription.Contract.GetLines</c>, <c>Subscription.Contract.CreateInvoice</c>, <c>Subscription.Contract.PreviewInvoice</c>, <c>Subscription.Contract.UpdateLineDates</c> and <c>Subscription.Contract.UpdateExchangeRates</c> Bifrost message types.
/// Consolidating the help text per domain means a future domain-wide formatting change
/// only has to touch this file, instead of every Impl codeunit in the domain.
/// </summary>
codeunit 10035066 "Sub Con Help ori"
{
    Access = Internal;

    /// <summary>
    /// Returns the Markdown help document for the given message key. Returns an empty
    /// text when the key is not one of the message types covered by this codeunit.
    /// </summary>
    internal procedure GetHelpMarkdown(MessageKey: Text): Text
    var
        HelpBuilder: TextBuilder;
    begin
        case MessageKey of
            'Subscription.Contract.GetLines':
                begin
                    HelpBuilder.AppendLine('# Subscription.Contract.GetLines');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Overview');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Attaches Subscription Lines that are not yet on any contract to a customer Subscription');
                    HelpBuilder.AppendLine('Contract. The candidate lines are exactly the ones Microsoft''s own "Get Subscription Lines"');
                    HelpBuilder.AppendLine('action on the contract page would offer: invoiced via contract, not yet on a contract,');
                    HelpBuilder.AppendLine('owned by a customer, and not already fully expired.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Parameters');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Parameter | Type | Required | Description |');
                    HelpBuilder.AppendLine('| --- | --- | --- | --- |');
                    HelpBuilder.AppendLine('| contractNo | Code[20] | Yes | The Customer Subscription Contract to attach lines to. May also be supplied as the message subject. |');
                    HelpBuilder.AppendLine('| subscriptionHeaderNo | Code[20] | No | Restricts the candidates to lines on one Subscription. |');
                    HelpBuilder.AppendLine('| subscriptionLineEntryNos | Integer[] | No | Restricts the candidates to these Subscription Line entry numbers. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Example');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010",');
                    HelpBuilder.AppendLine('  "subscriptionHeaderNo": "SUB000010"');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Response Shape');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "status": "Success",');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010",');
                    HelpBuilder.AppendLine('  "linesAttached": 2,');
                    HelpBuilder.AppendLine('  "attachedLines": [');
                    HelpBuilder.AppendLine('    { "subscriptionLineEntryNo": 1001, "contractLineNo": 10000 },');
                    HelpBuilder.AppendLine('    { "subscriptionLineEntryNo": 1002, "contractLineNo": 20000 }');
                    HelpBuilder.AppendLine('  ],');
                    HelpBuilder.AppendLine('  "linesSkipped": 1');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('A candidate line is skipped, rather than causing an error, when its Subscription''s');
                    HelpBuilder.AppendLine('End-User Customer No. does not match the contract''s Sell-to Customer No. `linesSkipped`');
                    HelpBuilder.AppendLine('counts these. A run that matches no candidates at all is still a success, with');
                    HelpBuilder.AppendLine('`linesAttached` of 0.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Errors');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Condition | Message |');
                    HelpBuilder.AppendLine('| --- | --- |');
                    HelpBuilder.AppendLine('| The contract does not exist | The Customer Subscription Contract ''%1'' does not exist. |');
                    HelpBuilder.AppendLine('| subscriptionLineEntryNos is present but is not an array | The parameter ''subscriptionLineEntryNos'' must be a JSON array. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Errors return `{ "status": "Error", "error": "...", "callstack": "..." }` and nothing is written.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Safety');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('This message type writes. It only attaches existing Subscription Lines to the contract -');
                    HelpBuilder.AppendLine('no Subscription Line is created and nothing is billed. The write runs in an isolated');
                    HelpBuilder.AppendLine('transaction that rolls back on error.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Related Message Types');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('- `Subscription.Line.Create`');
                    HelpBuilder.AppendLine('- `Subscription.Contract.CreateInvoice`');
                end;
            'Subscription.Contract.CreateInvoice':
                begin
                    HelpBuilder.AppendLine('# Subscription.Contract.CreateInvoice');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Overview');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Bills one customer Subscription Contract to an unposted sales invoice (or credit memo,');
                    HelpBuilder.AppendLine('when a line calls for one). The due Subscription Lines on the contract are copied into a');
                    HelpBuilder.AppendLine('temporary set and handed to Microsoft''s ad-hoc billing proposal entry point - the same');
                    HelpBuilder.AppendLine('entry point the per-contract billing dialog in the client uses - which creates Billing');
                    HelpBuilder.AppendLine('Line proposal rows with no billing template attached. The document is then created from');
                    HelpBuilder.AppendLine('those rows. Nothing is posted, and the document is never opened.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Parameters');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Parameter | Type | Required | Description |');
                    HelpBuilder.AppendLine('| --- | --- | --- | --- |');
                    HelpBuilder.AppendLine('| contractNo | Code[20] | Yes | The Customer Subscription Contract to bill. May also be supplied as the message subject. |');
                    HelpBuilder.AppendLine('| billingDate | Date | No | Lines due on or before this date are billed. Defaults to the work date. |');
                    HelpBuilder.AppendLine('| billingToDate | Date | No | Bills complete periods up to this date. Omit to use each line''s own billing rhythm. |');
                    HelpBuilder.AppendLine('| documentDate | Date | No | Document date on the created document. Defaults to the work date. |');
                    HelpBuilder.AppendLine('| postingDate | Date | No | Posting date on the created document. Defaults to the work date. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Dates use the ISO format `YYYY-MM-DD`.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Example');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010",');
                    HelpBuilder.AppendLine('  "billingDate": "2026-08-31"');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Response Shape');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "status": "Success",');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010",');
                    HelpBuilder.AppendLine('  "billingDate": "2026-08-31",');
                    HelpBuilder.AppendLine('  "documents": [');
                    HelpBuilder.AppendLine('    { "documentType": "Invoice", "documentNo": "SINV-000123" }');
                    HelpBuilder.AppendLine('  ],');
                    HelpBuilder.AppendLine('  "billingLineCount": 3');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('When nothing on the contract is due, the call still succeeds with `documents: []` and a');
                    HelpBuilder.AppendLine('`message` explaining that nothing was due.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Errors');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Condition | Message |');
                    HelpBuilder.AppendLine('| --- | --- |');
                    HelpBuilder.AppendLine('| The contract does not exist | The Customer Subscription Contract ''%1'' does not exist. |');
                    HelpBuilder.AppendLine('| Another contract has pending template-less proposal lines | Contract ''%1'' has %2 pending billing line(s) with no billing template assigned... |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Errors return `{ "status": "Error", "error": "...", "callstack": "..." }` and nothing is written.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Safety');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('This message type writes an unposted document; it never posts and never opens a page.');
                    HelpBuilder.AppendLine('The proposal rows this call creates carry a blank Billing Template Code, because that is');
                    HelpBuilder.AppendLine('what the ad-hoc, per-contract billing entry point produces. Microsoft''s own document');
                    HelpBuilder.AppendLine('creation codeunit converts every blank-template Billing Line in the company when it runs -');
                    HelpBuilder.AppendLine('not only the ones for this contract - so before doing anything this call checks for');
                    HelpBuilder.AppendLine('blank-template Billing Lines that belong to a different contract and refuses to run,');
                    HelpBuilder.AppendLine('naming that contract, rather than silently invoicing someone else''s pending proposal.');
                    HelpBuilder.AppendLine('The write runs in an isolated transaction that rolls back on error.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Related Message Types');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('- `Subscription.Contract.PreviewInvoice`');
                    HelpBuilder.AppendLine('- `Subscription.Contract.GetLines`');
                    HelpBuilder.AppendLine('- `Subscription.Billing.CreateProposal`');
                end;
            'Subscription.Contract.PreviewInvoice':
                begin
                    HelpBuilder.AppendLine('# Subscription.Contract.PreviewInvoice');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Overview');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Shows what `Subscription.Contract.CreateInvoice` would bill for one customer Subscription');
                    HelpBuilder.AppendLine('Contract, without keeping anything and without ever creating a document. The due');
                    HelpBuilder.AppendLine('Subscription Lines are handed to the same ad-hoc billing proposal entry point the write');
                    HelpBuilder.AppendLine('call uses, so the reported lines, periods and amounts reflect what Business Central would');
                    HelpBuilder.AppendLine('actually produce. The proposal rows built for the preview are read and then deleted again.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Parameters');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Parameter | Type | Required | Description |');
                    HelpBuilder.AppendLine('| --- | --- | --- | --- |');
                    HelpBuilder.AppendLine('| contractNo | Code[20] | Yes | The Customer Subscription Contract to preview. May also be supplied as the message subject. |');
                    HelpBuilder.AppendLine('| billingDate | Date | No | Lines due on or before this date are billed. Defaults to the work date. |');
                    HelpBuilder.AppendLine('| billingToDate | Date | No | Bills complete periods up to this date. Omit to use each line''s own billing rhythm. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Dates use the ISO format `YYYY-MM-DD`. There are no `documentDate` or `postingDate`');
                    HelpBuilder.AppendLine('parameters - a preview never creates a document, so no document dates apply.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Example');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010",');
                    HelpBuilder.AppendLine('  "billingDate": "2026-08-31"');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Response Shape');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "status": "Success",');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010",');
                    HelpBuilder.AppendLine('  "billingDate": "2026-08-31",');
                    HelpBuilder.AppendLine('  "lines": [');
                    HelpBuilder.AppendLine('    { "subscriptionLineEntryNo": 1001, "billingFrom": "2026-08-01", "billingTo": "2026-08-31", "unitPrice": "99.00", "amount": "99.00" }');
                    HelpBuilder.AppendLine('  ],');
                    HelpBuilder.AppendLine('  "wouldBillLineCount": 1,');
                    HelpBuilder.AppendLine('  "totalAmount": "99.00",');
                    HelpBuilder.AppendLine('  "preview": true,');
                    HelpBuilder.AppendLine('  "rollback": true');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('When nothing on the contract is due, the call still succeeds with `lines: []`,');
                    HelpBuilder.AppendLine('`wouldBillLineCount: 0` and a `message` explaining that nothing was due.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Errors');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Condition | Message |');
                    HelpBuilder.AppendLine('| --- | --- |');
                    HelpBuilder.AppendLine('| The contract does not exist | The Customer Subscription Contract ''%1'' does not exist. |');
                    HelpBuilder.AppendLine('| Another contract has pending template-less proposal lines | Contract ''%1'' has %2 pending billing line(s) with no billing template assigned... |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Errors return `{ "status": "Error", "error": "...", "callstack": "..." }`.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Safety');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Nothing is left behind, but this is not a rolled-back transaction: Microsoft''s billing');
                    HelpBuilder.AppendLine('proposal codeunit commits internally partway through its own run, so an ordinary error-based');
                    HelpBuilder.AppendLine('rollback would not undo it. Instead, this call notes the last Billing Line entry number');
                    HelpBuilder.AppendLine('before it does anything, builds the real proposal lines for the contract''s due Subscription');
                    HelpBuilder.AppendLine('Lines with that same entry point, reads back exactly the rows it just created, and then');
                    HelpBuilder.AppendLine('deletes exactly those rows again - on both the success path and if the proposal call itself');
                    HelpBuilder.AppendLine('fails partway through. No document is ever created, even temporarily: this call never');
                    HelpBuilder.AppendLine('reaches the step that turns proposal lines into an invoice. The same blank-template billing');
                    HelpBuilder.AppendLine('line caveat as `Subscription.Contract.CreateInvoice` applies: another contract''s pending');
                    HelpBuilder.AppendLine('template-less proposal lines block the preview so it cannot touch them, even temporarily.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Related Message Types');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('- `Subscription.Contract.CreateInvoice`');
                    HelpBuilder.AppendLine('- `Subscription.Contract.GetLines`');
                end;
            'Subscription.Contract.UpdateLineDates':
                begin
                    HelpBuilder.AppendLine('# Subscription.Contract.UpdateLineDates');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Overview');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('**This message type is blocked. It is registered so it can be discovered and documented,');
                    HelpBuilder.AppendLine('but every call returns an error - nothing is ever written.**');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('In the Business Central client, the "Update Subscription Line Dates" action on a Customer');
                    HelpBuilder.AppendLine('Subscription Contract rolls forward the term start and end dates on the contract''s');
                    HelpBuilder.AppendLine('Subscription Lines. That action calls');
                    HelpBuilder.AppendLine('`Customer Subscription Contract.UpdateServicesDates()`, which in turn calls');
                    HelpBuilder.AppendLine('`Subscription Header.UpdateServicesDates()` and codeunit 8058');
                    HelpBuilder.AppendLine('"Update Sub. Lines Term. Dates". All three are marked `internal` (the codeunit is');
                    HelpBuilder.AppendLine('`Access = Internal`) in Microsoft''s Subscription Billing app, so an external app such as');
                    HelpBuilder.AppendLine('this one cannot call them, and there is no other supported route to the same result.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('Re-implementing the date rollover logic independently was considered and rejected: the');
                    HelpBuilder.AppendLine('rules for term dates, billing rhythms and renewal interact in ways that are easy to get');
                    HelpBuilder.AppendLine('subtly wrong, and a divergent implementation could corrupt customer contracts in a way');
                    HelpBuilder.AppendLine('that is hard to detect and hard to undo.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Parameters');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Parameter | Type | Required | Description |');
                    HelpBuilder.AppendLine('| --- | --- | --- | --- |');
                    HelpBuilder.AppendLine('| contractNo | Code[20] | Yes | Accepted for documentation purposes only. May be supplied as the message subject. The call still fails regardless of its value. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Example');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010"');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Response Shape');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "status": "Error",');
                    HelpBuilder.AppendLine('  "error": "Subscription.Contract.UpdateLineDates has no supported public API...",');
                    HelpBuilder.AppendLine('  "callstack": "..."');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Errors');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Condition | Message |');
                    HelpBuilder.AppendLine('| --- | --- |');
                    HelpBuilder.AppendLine('| Always | Subscription.Contract.UpdateLineDates has no supported public API in this Business Central version... Run the ''Update Subscription Line Dates'' action on the contract in the Business Central client instead, or schedule Microsoft''s own job queue entry for the batch job that does this in bulk. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Safety');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('This message type never writes. It always responds with an error and never reaches the');
                    HelpBuilder.AppendLine('isolated write process, so there is nothing to roll back.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Related Message Types');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('- `Subscription.Contract.UpdateExchangeRates` (also blocked, for a different reason)');
                    HelpBuilder.AppendLine('- `Subscription.Contract.CreateInvoice`');
                end;
            'Subscription.Contract.UpdateExchangeRates':
                begin
                    HelpBuilder.AppendLine('# Subscription.Contract.UpdateExchangeRates');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Overview');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('**This message type is blocked. It is registered so it can be discovered and documented,');
                    HelpBuilder.AppendLine('but every call returns an error - nothing is ever written.**');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('In the Business Central client, the "Update Exchange Rates" action on a Customer');
                    HelpBuilder.AppendLine('Subscription Contract recalculates the local-currency amounts on the contract''s foreign');
                    HelpBuilder.AppendLine('currency Subscription Lines. That action calls');
                    HelpBuilder.AppendLine('`Customer Subscription Contract.UpdateAndRecalculateServiceCommitmentCurrencyData()`, which');
                    HelpBuilder.AppendLine('is marked `internal` in Microsoft''s Subscription Billing app, so an external app such as');
                    HelpBuilder.AppendLine('this one cannot call it.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('There is a second, independent reason this stays blocked even if that procedure were made');
                    HelpBuilder.AppendLine('public: the flow it drives opens the interactive "Exchange Rate Selection" page so a user');
                    HelpBuilder.AppendLine('can confirm which exchange rate to apply. When `GuiAllowed` is false - as it is for an');
                    HelpBuilder.AppendLine('unattended Bifrost call - that page returns false instead of failing, and the flow');
                    HelpBuilder.AppendLine('proceeds by applying a zero exchange rate. Calling it from here would silently zero out');
                    HelpBuilder.AppendLine('foreign-currency amounts on the contract, which is worse than not running it at all.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Parameters');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Parameter | Type | Required | Description |');
                    HelpBuilder.AppendLine('| --- | --- | --- | --- |');
                    HelpBuilder.AppendLine('| contractNo | Code[20] | Yes | Accepted for documentation purposes only. May be supplied as the message subject. The call still fails regardless of its value. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Request Example');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "contractNo": "CC000010"');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Response Shape');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('```json');
                    HelpBuilder.AppendLine('{');
                    HelpBuilder.AppendLine('  "status": "Error",');
                    HelpBuilder.AppendLine('  "error": "Subscription.Contract.UpdateExchangeRates has no supported public API...",');
                    HelpBuilder.AppendLine('  "callstack": "..."');
                    HelpBuilder.AppendLine('}');
                    HelpBuilder.AppendLine('```');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Errors');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('| Condition | Message |');
                    HelpBuilder.AppendLine('| --- | --- |');
                    HelpBuilder.AppendLine('| Always | Subscription.Contract.UpdateExchangeRates has no supported public API in this Business Central version... Use the ''Update Exchange Rates'' action on the contract in the Business Central client instead. |');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Safety');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('This message type never writes. It always responds with an error and never reaches the');
                    HelpBuilder.AppendLine('isolated write process, so there is nothing to roll back, and no risk of the zero exchange');
                    HelpBuilder.AppendLine('rate problem described above ever reaching a real contract through this API.');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('## Related Message Types');
                    HelpBuilder.AppendLine();
                    HelpBuilder.AppendLine('- `Subscription.Contract.UpdateLineDates` (also blocked, for a different reason)');
                    HelpBuilder.AppendLine('- `Subscription.Contract.CreateInvoice`');
                end;
            else
                exit('');
        end;
        exit(HelpBuilder.ToText());
    end;
}
